export const ASCENDING_PRODUCTS = "ASCENDING_PRODUCTS";
export const DESCENDING_PRODUCTS = "DESCENDING_PRODUCTS";
export const FILTER_PRODUCTS = "FILTER_PRODUCTS";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_ERROR = "FETCH_ERROR";